version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - "PORT=8080"
  db:
    image: "postgres:11"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: